src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

     /**
     * @Assert\File(
     *     maxSize = "10M",
     *     mimeTypes = {"image/*"},
     *     mimeTypesMessage = "Please upload a valid image"
     * )
     * 
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        if ($image != null) {
            $this->image = $image;
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(?\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('price')
            ->add('quantity')
            ->add('description')
            ->add('Category',
                    EntityType::class,
                    [
                        'class' => Category::class,
                        'choice_label' => 'name',
                        'multiple' => false,
                        'expanded' => false
                    ]
            )
            ->add('image', 
                    FileType::class,
                    [
                        // 'label' => 'Product Image',
                        'data_class' => null,
                        'required' => is_null($builder->getData()->getImage())
                    ]
            )
            ->add('date', 
                    DateType::class,
                    [
                        'widget' => 'single_text'
                    ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

use function PHPUnit\Framework\throwException;

/**
 * @IsGranted("ROLE_USER")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/product", name="product_index")
     */
    public function indexProduct()
    {
        $Products = $this->getDoctrine()
            ->getRepository(Product::class)
            ->findAll();
        return $this->render(
            'Product/index.html.twig',
            [
                'products' => $Products
            ]
        );
    }
    /**
     * @Route("/product/detail/{id}", name ="product_detail")
     */
    public function detailProduct($id)
    {
        $Product = $this->getDoctrine()->getRepository(Product::class)->find($id);
        return $this->render(
            "Product/detail.html.twig",
            [
                "product" => $Product
            ]
        );
    }
    /**
     * @IsGranted("ROLE_ADMIN")
     *
     * @Route("/Product/create", name="product_create")
     */
    public function createnewProduct(Request $request)
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $product->getImage();
            $fileName = md5(uniqid());
            $fileExtension = $image->guessExtension();
            $imageName = $fileName . '.' . $fileExtension;
            try {
                $image->move(
                    $this->getParameter('guitar_image'),
                    $imageName
                );
            } catch (FileException $e) {
                throwException($e);
            }
            //set imageName to database
            $product->setImage($imageName);
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($product);
            $manager->flush();
            $this->addFlash("Info", "Add successfully !");
            return $this->redirectToRoute("product_index");
        }

        return $this->render(
            "Product/create.html.twig",
            [
                'form' => $form->createView()
            ]
        );
    }
    /**
     * @IsGranted("ROLE_ADMIN")
     *
     * @Route ("/Product/update/{id}", name="product_update")
     */
    public function updateProduct(Request $request, $id)
    {
        $product = $this->getDoctrine()->getRepository(Product::class)->find($id);
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadFile = $form['image']->getData();
            if ($uploadFile != null) {
                //get Image from uploaded file
                $image = $product->getImage();

                //create an unique image name
                $fileName = md5(uniqid());
                //get image extension
                $fileExtension = $image->guessExtension();
                //merge image name & image extension => get a complete image name
                $imageName = $fileName . '.' . $fileExtension;

                //move upload file to a predefined location
                try {
                    $image->move(
                        $this->getParameter('guitar_image'),
                        $imageName
                    );
                } catch (FileException $e) {
                    throwException($e);
                }

                //set imageName to database
                $product->setImage($imageName);
            }

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($product);
            $manager->flush();

            $this->addFlash("Info", "Update product succeed !");
            return $this->redirectToRoute("product_index");
        }

        return $this->render(
            'product/update.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @IsGranted("ROLE_STAFF")
     * @Route("/Product/delete/{id}", name="product_delete")
     */

    public function deleteProduct($id)
    {
        $Product = $this->getDoctrine()
            ->getRepository(Product::class)
            ->find($id);
        if ($Product == null) {
            $this->addFlash("Error", "Delete failed !");
            return $this->redirectToRoute("product_index");
        }
        //if genre is not null
        $manager = $this->getDoctrine()
            ->getManager();
        $manager->remove($Product);
        $manager->flush();
        $this->addFlash("Info", "Delete succeed !");
        return $this->redirectToRoute("product_index");
    }
}

templates/product/create.html.twig
{% extends "base.html.twig" %}
{% block title %} Create new Product {% endblock %}

{% block body %}
<div class="container">
    <h2 class="mt-5 mb-5 text-center text-success"> CREATE Product </h2>
    <div class="col-md-6 offset-md-3"></div>
    {{ form_start (form) }}
        <div class="form-group">
            <h6 class="text-primary"> Product Name </h6>
            {{ form_widget (form.name, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Price </h6>
            {{ form_widget (form.price, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Quantity </h6>
            {{ form_widget (form.quantity, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Description </h6>
            {{ form_widget (form.description, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Image </h6>
            {{ form_widget (form.image, {'attr' : {'class' : 'form-control'}}) }}
        </div>
         <div class="form-group mt-2">
            <h6 class="text-primary"> Product Date </h6>
            {{ form_widget (form.date, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Category </h6>
            {{ form_widget (form.Category, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group text-center mt-5">
            <button class="btn btn-info mt-2">CREATE</button>
        </div>
    {{ form_end (form) }}
</div>
{% endblock %}

templates/product/detail.html.twig
{% extends "base.html.twig" %}

{% block title %} Product Detail {% endblock %}

{% block body %}
<style>
    body {
        width: 80%;
        margin: 20px auto;
    }
</style>
    <a class="btn btn-outline-success" href="{{ path ('product_index')}}">Back to list</a>
    <br><br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th> 
                <th scope="col">Description</th>
                <th scope="col">Quantity</th> 
                <th scope="col">Image</th>
                <th scope="col">Date</th>
                <th scope="col">Category</th> 
                <th scope="col">Actions</th> 
                
                
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row"> {{ product.id }} </td>
                <td scope="row"> {{ product.name }} </td>
                <td scope="row"> {{ product.price }} USD </td>
                <td scope="row"> {{ product.description }} </td>
                <td scope="row"> {{ product.quantity }} </td>
                <td scope="row"> 
                    {% if product.image == null %}
                         <img src="{{ asset ('images/Guitar/product.jpg')}}" width="80px" height="80px"> 
                    {% else %}               
                         <img src="{{ asset ('images/Guitar/' ~ product.image)}}" width="80px" height="80px">  
                    {% endif %}     
                </td>
                <td scope="row">
                     {{product.Date | date("d/m/Y")}}
                </td>
                <td scope="row">
                         <a href="{{ path ('category_detail', {'id' : product.category.id} ) }} "> 
                                           {{ product.category.name }} 
                         </a>
                </td>    
                <td scope="row">
                    <a class="btn btn-warning" href="{{ path ('product_update', {'id' : product.id} )}}">Update</a>
                    <a class="btn btn-danger" href="{{ path ('product_delete', {'id' : product.id} )}}"  
                                              onclick = "return confirm ('Are you sure to delete ?')" >      
                    Delete</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

templates/product/index.html.twig
{% extends "base.html.twig" %}

{% block title %} Product List {% endblock %}

{% block body %}
<style>
    body {
        width: 80%;
        margin: auto;
    }
</style>
 
<div class="container-fluid">
    <div class="container">
        {% for flash in app.flashes("Info") %}
            <p class="alert alert-success"> {{ flash }}
        {% endfor %}
        {% for flash in app.flashes("Error") %}
            <p class="alert alert-danger"> {{ flash }}
        {% endfor %}
    </div>
    <a class="btn btn-outline-success" href="{{ path ('product_create') }}">CREATE NEW PRODUCT</a>
    <br><br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th> 
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td scope="row"> {{ product.id }} </td>
                <td scope="row"> {{ product.name }} </td>
                <td>
                    <a class="btn btn-warning" href="{{ path ('product_detail', {'id' : product.id} )}}">Detail</a>   
                    <a class="btn btn-warning" href="{{ path ('product_update', {'id' : product.id} )}}">Update</a>
                    <a class="btn btn-danger" href="{{ path ('product_delete', {'id' : product.id} )}}"  
                                              onclick = "return confirm ('Are you sure to delete ?')" >      
                    Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/product/update.html.twig
{% extends "base.html.twig" %}
{% block title %} Update Product{% endblock %}
{% block body %}
<div class="container">
    <h2 class="mt-5 mb-5 text-center"> UPDATE PRODUCT </h2>
    <div class="col-md-6 offset-md-3"></div>
    {{ form_start (form) }}
        <div class="form-group">
            <h6 class="text-primary"> Product Name </h6>
            {{ form_widget (form.name, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Price </h6>
            {{ form_widget (form.price, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Quantity </h6>
            {{ form_widget (form.quantity, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Description </h6>
            {{ form_widget (form.description, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Image </h6>
            {{ form_widget (form.image, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> Product Date </h6>
            {{ form_widget (form.date, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group mt-2">
            <h6 class="text-primary"> product Genre </h6>
            {{ form_widget (form.Category, {'attr' : {'class' : 'form-control'}}) }}
        </div>
        <div class="form-group text-center mt-5">
            <button class="btn btn-info mt-2">UPDATE</button>
        </div>
    {{ form_end (form) }}
</div>
{% endblock %}